// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/ranking': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ranking.get').default>>>>
    }
    '/api/rooms': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/rooms.get').default>>>>
    }
    '/api/rooms/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/rooms/[id].get').default>>>>
    }
    '/api/rooms/:id/chat': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/rooms/[id]/chat.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/rooms/[id]/chat.post').default>>>>
    }
    '/api/rooms/:id/join': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/rooms/[id]/join.post').default>>>>
    }
    '/api/rooms/:id/leave': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/rooms/[id]/leave.post').default>>>>
    }
    '/api/rooms/:id/study': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/rooms/[id]/study.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}