// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2026/5/10 18:52:03
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/lizhenhu/Desktop/zhihe-0508-5/study-room/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/lizhenhu/Desktop/zhihe-0508-5/study-room/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/lizhenhu/Desktop/zhihe-0508-5/study-room/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/lizhenhu/Desktop/zhihe-0508-5/study-room/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/lizhenhu/Desktop/zhihe-0508-5/study-room/plugins/**/*.{js,ts,mjs}","/Users/lizhenhu/Desktop/zhihe-0508-5/study-room/composables/**/*.{js,ts,mjs}","/Users/lizhenhu/Desktop/zhihe-0508-5/study-room/utils/**/*.{js,ts,mjs}","/Users/lizhenhu/Desktop/zhihe-0508-5/study-room/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/lizhenhu/Desktop/zhihe-0508-5/study-room/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/lizhenhu/Desktop/zhihe-0508-5/study-room/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/lizhenhu/Desktop/zhihe-0508-5/study-room/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;